GET http://localhost:3000/

###

GET http://localhost:3000/getCommunities

###

POST http://localhost:3000/submitCommunity HTTP/1.1
content-type: application/json

{
    "name": "Dagmawi Babi",
    "link": "@Dagmawi_Babi",
    "description": "Believer | Creative Developer",
    "owner": "@DagmawiBabi",
    "tags": ["Tech","Spiritual", "News"],
    "type": "channel"
}
